[build]
publish = "public"
command = "hugo --gc --minify"
baseUrl = "https://agitated-kowalevski-811886.netlify.com/blog"

[context.production.environment]
HUGO_VERSION = "0.58.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.58.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture"

[context.deploy-preview.environment]
HUGO_VERSION = "0.58.3"

[context.branch-deploy]
command = "hugo --gc --minify"

[context.branch-deploy.environment]
HUGO_VERSION = "รง"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
