[build]
publish = "public"
command = "hugo --gc --minify"
baseUrl = "https://www.storj.io/blog"

[context.production.environment]
HUGO_VERSION = "0.58.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.58.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture"

[context.deploy-preview.environment]
HUGO_VERSION = "0.58.3"

[context.branch-deploy]
command = "hugo --gc --minify"

[context.branch-deploy.environment]
HUGO_VERSION = "รง"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/"
to = "https://tardigrade.io/blog/post/engineering/getting-from-petabytes-to-exabytes-the-road-ahead/"
status = 301
force = true
